version: '3'
services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
            - "8001:80"
    ssh:
        build:
            context: ./ssh
            dockerfile: Dockerfile
        ports:
            - "8822:22"
      
                        