version: '3'
services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
            - "8001:80"
        volumes:
            - ./php:/var/www/html
                        